const HTTP_OK_STATUS = 200;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;
const HTTP_SERVER_ERR = 500;

module.exports = { 
  HTTP_OK_STATUS,
  HTTP_BAD_REQUEST,
  HTTP_UNAUTHORIZED,
  HTTP_SERVER_ERR,
};